### PR TITLE
TST: disable tests compiling Cython code on Python 3.12

### LINKED ISSUE #337: Failing tests
Python 3.12 alpha 6 was released 6 days ago, and now the 3.12 job is failing on #291 because a Cython module isn't building. The PR is unrelated, so given the very close Python release, I suspect this is just more breaking in Cython. Opening this now to log, will investigate later.

```
[1/6] Generating mypkg/generate-config-file with a custom command
[2/6] Compiling C object mypkg/extmod.cpython-312-x86_64-linux-gnu.so.p/extmod.c.o
[3/6] Linking target mypkg/extmod.cpython-312-x86_64-linux-gnu.so
[4/6] Compiling Cython source /home/runner/work/meson-python/meson-python/tests/packages/scipy-like/mypkg/cy_extmod.pyx
[5/6] Compiling C object mypkg/cy_extmod.cpython-312-x86_64-linux-gnu.so.p/meson-generated_mypkg_cy_extmod.pyx.c.o
FAILED: mypkg/cy_extmod.cpython-312-x86_64-linux-gnu.so.p/meson-generated_mypkg_cy_extmod.pyx.c.o 
cc -Imypkg/cy_extmod.cpython-312-x86_64-linux-gnu.so.p -Imypkg -I../../mypkg -I/opt/hostedtoolcache/Python/3.12.0-alpha.6/x64/include/python3.12 -fvisibility=hidden -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -w -O2 -fPIC -MD -MQ mypkg/cy_extmod.cpython-312-x86_64-linux-gnu.so.p/meson-generated_mypkg_cy_extmod.pyx.c.o -MF mypkg/cy_extmod.cpython-312-x86_64-linux-gnu.so.p/meson-generated_mypkg_cy_extmod.pyx.c.o.d -o mypkg/cy_extmod.cpython-312-x86_64-linux-gnu.so.p/meson-generated_mypkg_cy_extmod.pyx.c.o -c mypkg/cy_extmod.cpython-312-x86_64-linux-gnu.so.p/mypkg/cy_extmod.pyx.c
mypkg/cy_extmod.cpython-312-x86_64-linux-gnu.so.p/mypkg/cy_extmod.pyx.c: In function ‘__Pyx_PyErr_ExceptionMatchesInState’:
mypkg/cy_extmod.cpython-312-x86_64-linux-gnu.so.p/mypkg/cy_extmod.pyx.c:2247:32: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘curexc_type’
 2247 |     PyObject *exc_type = tstate->curexc_type;
      |                                ^~
mypkg/cy_extmod.cpython-312-x86_64-linux-gnu.so.p/mypkg/cy_extmod.pyx.c: In function ‘__Pyx_ErrRestoreInState’:
mypkg/cy_extmod.cpython-312-x86_64-linux-gnu.so.p/mypkg/cy_extmod.pyx.c:2260:22: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘curexc_type’
 2260 |     tmp_type = tstate->curexc_type;
      |                      ^~
mypkg/cy_extmod.cpython-312-x86_64-linux-gnu.so.p/mypkg/cy_extmod.pyx.c:2261:23: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘curexc_value’
 2261 |     tmp_value = tstate->curexc_value;
      |                       ^~
mypkg/cy_extmod.cpython-312-x86_64-linux-gnu.so.p/mypkg/cy_extmod.pyx.c:2262:20: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘curexc_traceback’
 2262 |     tmp_tb = tstate->curexc_traceback;
      |                    ^~
mypkg/cy_extmod.cpython-312-x86_64-linux-gnu.so.p/mypkg/cy_extmod.pyx.c:2263:11: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘curexc_type’
 2263 |     tstate->curexc_type = type;
      |           ^~
mypkg/cy_extmod.cpython-312-x86_64-linux-gnu.so.p/mypkg/cy_extmod.pyx.c:2264:11: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘curexc_value’
 2264 |     tstate->curexc_value = value;
      |           ^~
mypkg/cy_extmod.cpython-312-x86_64-linux-gnu.so.p/mypkg/cy_extmod.pyx.c:2265:11: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘curexc_traceback’
 2265 |     tstate->curexc_traceback = tb;
      |           ^~
mypkg/cy_extmod.cpython-312-x86_64-linux-gnu.so.p/mypkg/cy_extmod.pyx.c: In function ‘__Pyx_ErrFetchInState’:
mypkg/cy_extmod.cpython-312-x86_64-linux-gnu.so.p/mypkg/cy_extmod.pyx.c:2271:19: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘curexc_type’
 2271 |     *type = tstate->curexc_type;
      |                   ^~
mypkg/cy_extmod.cpython-312-x86_64-linux-gnu.so.p/mypkg/cy_extmod.pyx.c:2272:20: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘curexc_value’
 2272 |     *value = tstate->curexc_value;
      |                    ^~
mypkg/cy_extmod.cpython-312-x86_64-linux-gnu.so.p/mypkg/cy_extmod.pyx.c:2273:17: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘curexc_traceback’
 2273 |     *tb = tstate->curexc_traceback;
      |                 ^~
mypkg/cy_extmod.cpython-312-x86_64-linux-gnu.so.p/mypkg/cy_extmod.pyx.c:2274:11: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘curexc_type’
 2274 |     tstate->curexc_type = 0;
      |           ^~
mypkg/cy_extmod.cpython-312-x86_64-linux-gnu.so.p/mypkg/cy_extmod.pyx.c:2275:11: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘curexc_value’
 2275 |     tstate->curexc_value = 0;
      |           ^~
mypkg/cy_extmod.cpython-312-x86_64-linux-gnu.so.p/mypkg/cy_extmod.pyx.c:2276:11: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘curexc_traceback’
 2276 |     tstate->curexc_traceback = 0;
      |           ^~
ninja: build stopped: subcommand failed.
```

### PR DESCRIPTION
**Pull request by dnicolodi**
Cython generated code does not compile with Python 3.12. This cab be revisited once the next beta version of Cython 3.0 is released.

Fixes #337.

### CODE REVIEW

**Comment by rgommers** [comment]
thanks!
